### ISSUE TITLE
Filter and display user traits instead of their IDs

### ISSUE THREAD

**Issue by WesleyYue** [SolidStateGroup/bullet-train-api#2853] opened 2023-10-17 21:28 UTC
**Is your feature request related to a problem? Please describe.**

It's frustrating to have to search for users using only unique IDs when we have emails attached as traits. Those IDs are not really helpful when you're trying to find someone specific.

![image](https://github.com/Flagsmith/flagsmith/assets/5280818/7fd7bd84-a17f-4aa2-a47e-1d005b216d88)

**Describe the solution you'd like**

It would be great if we could use the emails we've attached as traits for filtering and searching for users within Flagsmith.

**Describe alternatives you've considered**

Use emails directly as the IDs, but emails can change and do not uniquely identify a user.

**Additional context**

We use random unique IDs to sync users across our systems, but they're not really useful when you're just trying to look up a user in Flagsmith. Having the ability to filter and display users by traits like emails would make things a lot easier.

**Comment by matthewelwell** [comment] 2023-10-18 08:59
Duplicate of #444

**Closed as completed by matthewelwell** 2023-10-18 08:59 UTC
