### ISSUE TITLE
Feature Enhancement Request -  Change request creation when enabling Features directly or via Segments

### ISSUE THREAD

**Issue by DelineaLaari** [SolidStateGroup/bullet-train-api#2613] opened 2023-08-09 15:19 UTC
Generate a change request whenever a feature is enabled or enabled at a segment level. Currently, it seems that the change request feature only works when adding new feature flags.

**Comment by dabeeeenster** [comment] 2023-08-09 18:54
Duplicate of https://github.com/Flagsmith/flagsmith/issues/1204

**Closed as completed by dabeeeenster** 2023-08-09 18:54 UTC
