### ISSUE TITLE
Add new users to Mailerlite

### ISSUE THREAD

**Issue by ilyaazovtsev** [SolidStateGroup/bullet-train-api#597] opened 2021-12-15 14:02 UTC
Can we please pull all new users who sign up - directly to Mailerlite so we can provide an email onboarding 

Variables we need to send to Mailerlite: 
1. Email 
2. First Name
3. Last Name 
4. Is it a paid user or not

**Comment by dabeeeenster** [comment] 2021-12-15 14:58
Dupe of #565

**Closed as completed by dabeeeenster** 2021-12-15 14:58 UTC
