### ISSUE TITLE
A role without a tag should not have its permissions restricted.

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#4288] opened 2024-07-05 21:49 UTC
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [X] Some other way (add details in description below)

### Describe the bug

If a role without a tag should not have its permissions(`UPDATE_FEATURE_STATE` and/or `DELETE_FEATURE`) restricted.

### Steps To Reproduce

1. Create a role with View Project, View environment, and delete feature, and assign it to test user
2. Log in with the test user
3. Go to the project -> environment that you have permission to access.
4. Try to delete a feature
5.  Error 403

### Expected behavior

If there is no tag restricting the permissions, the feature should be deleted successfully.

CC @matthewelwell @gagantrivedi @kyle-ssg

**Comment by matthewelwell** [comment] 2024-07-08 15:24
@novakzaballa the example you have given in the description is not valid. The permission for deleting features is the `DELETE_FEATURE` at the project level. I'm going to close this issue but please re-open it if there is another valid reproduction scenario.

**Comment by novakzaballa** [comment] 2024-07-09 15:18
@matthewelwell I'm sorry, there was confusion in the PR description. I will correct this with the correct permission and reopen this issue

**Comment by novakzaballa** [comment] 2024-07-30 16:01
Related with https://github.com/Flagsmith/flagsmith/issues/1535

**Comment by gagantrivedi** [comment] 2024-08-26 06:07
@novakzaballa  I think this is a duplicate of https://github.com/Flagsmith/flagsmith/issues/4506 and was fixed here: https://github.com/Flagsmith/flagsmith-rbac/pull/24? Is that correct? I am not able to reproduce this

**Comment by gagantrivedi** [comment] 2024-08-26 06:22
> @novakzaballa I think this is a duplicate of #4506 and was fixed here: [Flagsmith/flagsmith-rbac#24](https://github.com/Flagsmith/flagsmith-rbac/pull/24)? Is that correct? I am not able to reproduce this

Ah, I am able to reproduce this if I tag the feature?

**Comment by novakzaballa** [comment] 2024-08-26 18:11
Hey @gagantrivedi, you’re right. The PR also resolved part of the issue with the roles in the same way. I’ll merge it along with my PR.

**Comment by gagantrivedi** [comment] 2024-10-21 08:59
Fixed in https://github.com/Flagsmith/flagsmith/pull/4523

**Closed as completed by gagantrivedi** 2024-10-21 08:59 UTC
Labels: bug
