### ISSUE TITLE
🐞 Bug - Webhook CORS header missing

### ISSUE THREAD

**Issue by Rikj000** [SolidStateGroup/bullet-train-api#496] opened 2021-11-17 15:05 UTC
Hi 👋

I'm currently testing out `Flagsmith` implementation in my software, 
however I'm having troubles with the *(feature)* Webhooks and I think I stumbled upon a bug.

### Setup Description
- Following Feature Webhook has been configured: http://localhost:8002/webhook/flagsmith
  *(Running on a localhost XAMPP PHP Laravel setup & using [Laravel-Flagsmith](https://github.com/clearlyip/laravel-flagsmith))*
- Flagsmith is running under Docker on: http://localhost:8000

### Bug Description
- Calling http://localhost:8002/webhook/flagsmith with a Post request through [Postman](https://www.postman.com/),
  **successfully triggers** the breakpoint in my application's [webhook logic](https://github.com/clearlyip/laravel-flagsmith/blob/main/src/Http/Controllers/Webhooks.php)
- Testing the http://localhost:8002/webhook/flagsmith endpoint through `Flagsmith`'s `Test Your Webhook` button,
  **does not trigger** the breakpoint in my application's [webhook logic](https://github.com/clearlyip/laravel-flagsmith/blob/main/src/Http/Controllers/Webhooks.php).
  However it does create following CORS errors in the console of the Web Developer Tools:
  ![Flagsmith-Webhook-CORS-Error](https://user-images.githubusercontent.com/24852597/142224273-55d6707a-7d40-4ac4-b7e6-37c657f5bdce.png)
  ```log
  Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8002/webhook/flagsmith. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
  Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8002/webhook/flagsmith. (Reason: CORS request did not succeed).
  Learn more: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
  ```

### BugFix suggestion
Whitelist defined Webhook URLs in the CORS headers 
*(Both when creating a new Webhook, but also when testing before actual creation of the webhook)*

**Comment by dabeeeenster** [comment] 2021-11-17 16:25
This is basically a duplicate of https://github.com/Flagsmith/flagsmith/issues/342 - the webhooks should not be tested in the browser but go via the API.

**Closed as completed by dabeeeenster** 2021-11-17 16:25 UTC
