### ISSUE TITLE
🐞 Bug - `ALLOW_SIGNUPS: 'false'` not working under `docker`

### ISSUE THREAD

**Issue by Rikj000** [SolidStateGroup/bullet-train-api#520] opened 2021-11-29 10:29 UTC
## What goes wrong?
When deploying under `docker` *(both locally & on Azure)* while setting `ALLOW_SIGNUPS: 'false'`, the sign-up link doesn't disappear.

![flagsmith-allow-signup-issue](https://user-images.githubusercontent.com/24852597/143600426-86db3cd5-07c5-41e5-b1bd-c07f4b81317d.png)

## How to replicate?
**Deploy to localhost through CLI:**
```bash
docker context use default
docker compose --file docker/docker-compose.yml up
```
**Deploy to Azure through CLI:**
```bash
docker login azure # => Web browser login
docker context create flagsmith
docker context use flagsmith
docker compose --file docker/docker-compose.yml up
```

This [**`docker-compose.yml`**](https://github.com/Flagsmith/flagsmith/files/7617446/docker-compose.yml.log) was used.
*(I appended `.log` to the file to be able to upload to GitHub + restored the password to `password`)*

- 📎 Link to start of the [**Discord Discussion**](https://discord.com/channels/517647859495993347/517647859966017541/913788327633760256) that lead to opening this issue & below issue.
- 📎 Link to Azure specific issue: https://github.com/Flagsmith/flagsmith/issues/517

**Comment by kyle-ssg** [comment] 2021-12-04 17:51
@dabeeeenster I believe this is just frontend https://github.com/Flagsmith/flagsmith/pull/545 - has been merged to main.

**Comment by Rikj000** [comment] 2021-12-07 16:07
> @dabeeeenster I believe this is just frontend #545 - has been merged to main.

I honestly doubt that.
Today I've been re-deploying to Azure docker containers using TerraForm,
while deploying the container on the latest flagsmith image.

I was trying out multiple environment settings configurations, and learned the following:
- Setting `ALLOW_SIGNUPS = "false"` or `ALLOW_SIGNUPS = 0` did not remove the `Not got an account? Sign Up` text
- Setting `PREVENT_SIGNUP = "true"` or `PREVENT_SIGNUP = 1` *(Disables the API endpoint for signups)* did:
    - Remove the `Not got an account? Sign Up` text
    - Results into inability to use invite links.
        When creating an invite link, logging out and navigating to the invite link,
        I'm prompted with a `Login to accept your invite` page where you can't register:
        ![flagsmith-login-to-accept-your-invite](https://user-images.githubusercontent.com/24852597/145063432-1dd0d53f-1ade-4c58-95c4-29a75009f2e6.png)
 
 Following TerraForm file was used for this:
 [aci-flagsmith-main.tf.log](https://github.com/Flagsmith/flagsmith/files/7669764/aci-flagsmith-main.tf.log)
 *(I appended `.log` to the file format to be able to upload it here + replaced the postgres password & hostname with `<password>` & `<host-id>` & switched our own DNS name label to a general `flagsmith`)*

**Comment by dabeeeenster** [comment] 2021-12-08 16:03
Hi @Rikj000 - sorry - I'm a bit lost now - is there an explanation of what the issue is you are facing?

**Comment by Rikj000** [comment] 2021-12-08 16:24
> Hi @Rikj000 - sorry - I'm a bit lost now - is there an explanation of what the issue is you are facing?

- `ALLOW_SIGNUPS` did nothing to the `Not got an account? Sign Up` text when toggled on/off 
*(While I think the expected behavior here would be that it would display the text if `"true"` & hide the text if `"false"`)*
- `PREVENT_SIGNUP = "true"` did hide the `Not got an account? Sign Up` text *(This is an API setting so I'm unsure why it's affecting the FrontEnd?)*, but this also breaks registration with an invite link as you can see [in the picture of my previous reply](https://github.com/Flagsmith/flagsmith/issues/520#issuecomment-988067169)!

Which renders it impossible for me to configure our Flagsmith instance with:
- A closed off sign-up system
- Ability to allow new members to join through invite links

Hope that explains it a little better 🙂

**Comment by matthewelwell** [comment] 2021-12-13 19:58
So, from what I can tell here, the issue relates to the fact that, when we added the ability to run the application in a single container, the environment variables got a little muddled. I believe that the `ALLOW_SIGNUPS` variable is completely redundant in the single container architecture (although it is still used when running the API and frontend application separately). 

Since, @Rikj000, you're using the single container architecture, we should therefore focus only on the `PREVENT_SIGNUP` variable and ignore the `ALLOW_SIGNUPS` var as you have already deduced. 

To answer the question as to why an API setting is affecting the FE; this is because, although it is _technically_ an API setting, it is actually accessed by the FE when it makes a call to `/config/project-overrides`. The API dynamically generates a JS file that it serves at this location which is used by the FE. For reference, you can see the API code for this [here](https://github.com/Flagsmith/flagsmith/blob/main/api/app/views.py#L32) and you can see the FE include this script [here](https://github.com/Flagsmith/flagsmith/blob/main/frontend/web/index.html#L26). You can also see this file being generated yourself by browsing to `https://your.domain.com/config/project-overrides`. 

As such, unless I am missing something, what this seems to boil down to is a FE bug that prevents users invited via a link from signing up when `PREVENT_SIGNUP` env var is set to a truthy value (or more specifically from a FE point of view, when the `projectOverrides.preventSignup=true`).

Thanks for the patience and detailed responses here @Rikj000. I'm going to get this one sorted for you and we'll let you know when a new version of the docker container is released which fixes this issue.

**Closed as completed** 2022-01-06 15:51 UTC
Labels: bug, api
