### ISSUE TITLE
Setting an Identity flag override to the Environment default doesn't trigger a webhook

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1589] opened 2022-11-02 11:46 UTC
1. Add a feature webhook to an environment
2. Create a flag `A`. Default to false.
3. Create an identity. 
4. Override the flag `A` to true for the identity.
5. Webhook triggers. 
6. Reset the user override by clicking the 'Reset' button
7. No webhook triggers. It should.

**Comment by matthewelwell** [comment] 2023-03-06 14:19
Duplicate of #148

**Closed as completed** 2023-03-06 14:19 UTC
Labels: bug, api, tech-debt

**Comment by nihaha** [comment] 2024-10-07 12:05
Any progress on this issue?

**Comment by matthewelwell** [comment] 2024-10-08 11:08
Hi @nihaha, this issue is closed. Please keep the discussion to the open issue #148.
