### ISSUE TITLE
Add the ability search for specific identities other than identifier field

### ISSUE THREAD

**Issue by gnumoreno** [SolidStateGroup/bullet-train-api#3251] opened 2024-01-08 14:53 UTC
**Is your feature request related to a problem? Please describe.**

Customers expressed the desire to be able to find identities easier. Currently our search is "starts with" or "exact match" and the identifier is also usually something like a primary key or uuid which makes it hard to find a particular user or identity.

**Describe the solution you'd like**

I'm not going to describe a solution here just wanted to report the gap in functionality. 

**Describe alternatives you've considered**

Some options that were mentioned: composite key (with the description being the first part), #444, #290, or just adding the description to the main page and making it searchable. 

**Additional context**

Came up in conversations with several customers.

**Comment by dabeeeenster** [comment] 2024-01-12 13:29
Dupe of https://github.com/Flagsmith/flagsmith/issues/444

**Closed as completed** 2024-01-12 13:30 UTC
