### ISSUE TITLE
Some fraction of evaluations are incorrect when there is a segment override with multiple OR conditions

### ISSUE THREAD

**Issue by nishant-shah-social** [SolidStateGroup/bullet-train-api#2618] opened 2023-08-09 21:48 UTC
**Describe the bug**

We are self hosting flagsmith in our cloud infrastructure via k8s.
We have around 100 feature flags and 65 segments in total. There is no more than 1 segment overridden by a feature flag. 
There are around 7 segments wherein we have more than 100 OR conditions.
We are running our sdks in local evaluation mode (golang and nodejs)
Golang SDK Version:- 3.1.0
NodeJS SDK Version:- 3.1.0

We are noticing around 1% of the total evaluations happening incorrectly. Mainly the feature flags where the overridden segment have more OR conditions involved (around 100), we are observing this behaviour.
Given the total number of evaluations are pretty high in our case, even 1% accounts to a really big number and has become a concern for us.
We are seeing this behaviour for both golang and nodeJS sdks

**How are you running Flagsmith?**

- [ ] Self Hosted with Docker
- [ _ ] Self Hosted with Kubernetes
- [ ] SaaS at flagsmith.com
- [ ] Some other way

**Additional context**

**Comment by dabeeeenster** [comment] 2023-08-10 07:56
This issue doesnt really give us enough to go on I'm afraid. 

- Are you able to provide a reproducable setup? 
- Is this using local or remote evaluation? 
- Is 1 flag incorrect, or more than 1?
- Are you using traits/identities? Does it consistently return incorrect flags for a specific identity?

**Comment by matthewelwell** [comment] 2023-08-22 14:24
Closing due to lack of sufficient information to reproduce.

**Closed as completed by matthewelwell** 2023-08-22 14:24 UTC
Labels: bug
