### ISSUE TITLE
Implement `setState(String:jsonFlags)` for all SDKs

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#1655] opened 2022-11-11 11:04 UTC
So you can provide state from a flat file/cache/in memory object.

As per https://docs.flagsmith.com/clients/javascript#providing-default-flags-as-part-of-cicd

**Comment by matthewelwell** [comment] 2023-04-11 11:18
Closing as duplicate of #2024.

**Closed as completed by matthewelwell** 2023-04-11 11:18 UTC
Labels: feature, sdk
