### ISSUE TITLE
Add Ability for OpenSource customers to provide company info in exchange for a dedicated support call

### ISSUE THREAD

**Issue by agregoryfs** [SolidStateGroup/bullet-train-api#3896] opened 2024-05-08 10:21 UTC
### Is your feature request related to a problem? Please describe.

People who install the opensource product are unknown. We want to give our customers a way to provide their company information to us in exchange for a support call with them. 

### Describe the solution you'd like.

On the OpenSource log in page, add a link that links to a marketing landing page where they can provide their company details. We can determine the exact language but it would a short text and a button for the hyperlink. "Are you a company with more than 10 employees? Provide your company information (email and company name) in exchange for a dedicated support call with someone on the team." The link will be connected to a marketing landing page where we can have the form as this will be on the open source on-premise product.

### Describe alternatives you've considered

Adding a dedicated page that is shown one time at first install. This is less desirable as it will only be shown for the installer. We want to give other users who are using the open source product to have a chance for easy support.

**Comment by matthewelwell** [comment] 2024-05-09 09:21
Duplicate of Flagsmith/flagsmith-private#16

**Closed as completed by matthewelwell** 2024-05-09 09:21 UTC
