### ISSUE TITLE
🐞 Bug - Azure `environment` variables not being detected correctly

### ISSUE THREAD

**Issue by Rikj000** [SolidStateGroup/bullet-train-api#517] opened 2021-11-26 15:11 UTC
## What goes wrong?
When deploying to Azure under docker while setting `ALLOW_SIGNUPS: 'false'`, the sign-up link doesn't disappear.

![flagsmith-allow-signup-issue](https://user-images.githubusercontent.com/24852597/143600426-86db3cd5-07c5-41e5-b1bd-c07f4b81317d.png)

While when checking under the Container Instance Properties on Azure, we can see that the variable indeed is configured as expected.

![flagsmith-azure-environment-vars](https://user-images.githubusercontent.com/24852597/143600826-6d7a16e8-958e-4742-8d3d-92c1cbc9d4d6.png)

## How to replicate?
Deploy to Azure through CLI:
```bash
docker login azure # => Web browser login
docker context create flagsmith
docker context use flagsmith
docker compose --file docker/docker-compose.yml up
```
This [**`docker-compose.yml`**](https://github.com/Flagsmith/flagsmith/files/7609472/docker-compose.yml.log) was used.
*(I appended `.log` to the file to be able to upload to GitHub + restored the password to `password`)*

Link to start of the [**Discord Discussion**](https://discord.com/channels/517647859495993347/517647859966017541/913788327633760256) that lead to opening this issue.

**Comment by kyle-ssg** [comment] 2021-12-04 17:52
I believe this is just a duplicate of https://github.com/Flagsmith/flagsmith/issues/520, tracking there.

**Closed as completed by kyle-ssg** 2021-12-04 17:52 UTC
Labels: bug, api
