### ISSUE TITLE
Implement bulk Identity Create/Update in Core API

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2315] opened 2023-06-19 10:01 UTC
https://docs.flagsmith.com/api/bulk-insert-identities-update

Currently exists in Edge API. We should implement it in the core API too. Related to https://github.com/Flagsmith/flagsmith/issues/1667

**Comment by matthewelwell** [comment] 2023-06-19 15:08
Closing as duplicate of https://github.com/Flagsmith/flagsmith/issues/1212

**Closed as completed by matthewelwell** 2023-06-19 15:08 UTC
Labels: improvement, api
