### ISSUE TITLE
The tag-based permission only validate some views

### ISSUE THREAD

**Issue by novakzaballa** [SolidStateGroup/bullet-train-api#4287] opened 2024-07-05 21:44 UTC
### How are you running Flagsmith

- [ ] Self Hosted with Docker
- [ ] Self Hosted with Kubernetes
- [X] SaaS at flagsmith.com
- [X] Some other way (add details in description below)

### Describe the bug

The tag-based permission with UPDATE_FEATURE_STATE only validates `FeatureStatePermissions` and not `EnvironmentFeatureStatePermissions`.
This last one is used when updating a feature state value from the feature modal.

### Steps To Reproduce

1. Create a role with View Project, View environment, and update feature state, add a tag, and assign it to test user
2. Log in with the test user
3. Go to the project -> environment that you have permission to access.
4. Select a feature and update the feature state
5. The feature state was updated successfully (This is an error)

### Expected behavior

If the feature does not have the same tag, the feature state value should not be updated.

CC: @matthewelwell @gagantrivedi @kyle-ssg

**Comment by matthewelwell** [comment] 2024-07-08 15:26
@gagantrivedi can you confirm if this is expected behaviour or not?

**Comment by gagantrivedi** [comment] 2024-07-09 02:31
> @gagantrivedi can you confirm if this is expected behaviour or not?


Looks like a legit issue to me

**Comment by gagantrivedi** [comment] 2024-08-26 06:05
@novakzaballa  I think this is a duplicate of https://github.com/Flagsmith/flagsmith/issues/4506 and was fixed here: https://github.com/Flagsmith/flagsmith-rbac/pull/24? Is that correct?

**Comment by gagantrivedi** [comment] 2024-10-21 09:04
Fixed in https://github.com/Flagsmith/flagsmith/pull/4523

**Closed as completed by gagantrivedi** 2024-10-21 09:04 UTC
Labels: bug
