### ISSUE TITLE
Search users by trait

### ISSUE THREAD

**Issue by KirioXX** [SolidStateGroup/bullet-train-api#1959] opened 2023-02-25 14:35 UTC
**Is your feature request related to a problem? Please describe.**
We have many users and use the user id as an identifier and the email as a trait.
What makes it quite hard to find a specific user.

**Describe the solution you'd like**
It would be great if we could search users by their traits to search all users whit a specific email domain 
or enable a feature just for one user.

**Describe alternatives you've considered**
-

**Additional context**
-

gz#452

**Comment by dabeeeenster** [comment] 2023-02-27 08:08
Closing this as a duplicate of https://github.com/Flagsmith/flagsmith/issues/444

**Closed as completed by dabeeeenster** 2023-02-27 08:08 UTC
