### ISSUE TITLE
Add "start trial" and "end trial" buttons on the Sales Dashboard org page

### ISSUE THREAD

**Issue by dabeeeenster** [SolidStateGroup/bullet-train-api#2784] opened 2023-09-16 07:41 UTC
Start Trial would:

- Create an Organisation subscription with Enterprise features, set to trail

End Trial would:

- Remove Organisation subscription record in DB

We should maybe add a payment method of Trial here?

**Comment by matthewelwell** [comment] 2023-10-17 10:45
Duplicate of #1716

**Closed as completed by matthewelwell** 2023-10-17 10:45 UTC
Labels: improvement, api
